require("config.set")
require("config.remap")
require("config.abbrev")
require("config.autocmd")
require("config.extui")
require("config.neovide")
require("config.core_plugins")
require("config.lsp")
