return {
	-- "folke/noice.nvim",
	-- event = "VeryLazy",
	-- dependencies = {
	-- 	-- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
	-- 	"MunifTanjim/nui.nvim",
	-- 	"rcarriga/nvim-notify",
	-- },
	-- config = function()
	-- 	require("notify").setup({
	-- 		timeout = 15000,
	-- 		render = "wrapped-compact",
	-- 		stages = "static",
	-- 		top_down = false,
	-- 	})
	-- 	require("noice").setup({
	-- 		lsp = {
	-- 			hover = {
	-- 				silent = true, -- set to true to not show a message if hover is not available
	-- 			},
	-- 			-- override markdown rendering so that **cmp** and other plugins use **Treesitter**
	-- 			override = {
	-- 				["vim.lsp.util.convert_input_to_markdown_lines"] = true,
	-- 				["vim.lsp.util.stylize_markdown"] = true,
	-- 				["cmp.entry.get_documentation"] = true, -- requires hrsh7th/nvim-cmp
	-- 			},
	-- 		},
	-- 		-- you can enable a preset for easier configuration
	-- 		presets = {
	-- 			bottom_search = false, -- use a classic bottom cmdline for search
	-- 			long_message_to_split = true, -- long messages will be sent to a split
	-- 			lsp_doc_border = true, -- add a border to hover docs and signature help
	-- 		},
	-- 	})
	-- end,
}
